package sketch.dyn.synth;

import sketch.util.CliOptGroup;

public class ScSynthesisOptions extends CliOptGroup {
    public ScSynthesisOptions() {
        prefixes("sy", "synth", "synthesis");
        add("--num_solutions", 1, "number of solutions to find");
        add("--num_threads", "number of threads (currently unsupported)");
        add("--print_exceptions", "print all exceptions raised by the sketch");
        add("--print_counterexamples", "print values generated by counterexamples");
        add("--debug_stop_after", -1, "stop after a number of runs");
    }
}
