/*
 * To change this template, choose Tools | Templates and open the template in the editor.
 */

/*
 * EntanglementGuiPanelBase.java Created on Nov 3, 2010, 11:22:34 AM
 */

package sketch.entanglement.ui;

/**
 * @author shaon
 */
public class EntanglementGuiPanelBase extends javax.swing.JPanel {

    /** Creates new form EntanglementGuiPanelBase */
    public EntanglementGuiPanelBase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        partitionScrollPane = new javax.swing.JScrollPane();
        verticalSplitPane = new javax.swing.JSplitPane();
        programScrollPane = new javax.swing.JScrollPane();
        programEditorPane = new javax.swing.JEditorPane();
        debugPanel = new javax.swing.JPanel();
        debugLabel = new javax.swing.JLabel();
        debugScrollPane = new javax.swing.JScrollPane();
        debugEditorPane = new javax.swing.JEditorPane();
        frameLabel = new javax.swing.JLabel();
        refineTraceButton = new javax.swing.JButton();
        entanglementScrollPane = new javax.swing.JScrollPane();
        refineAngelButton = new javax.swing.JButton();

        splitPane.setDividerLocation(266);
        splitPane.setLeftComponent(partitionScrollPane);

        verticalSplitPane.setDividerLocation(230);
        verticalSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        programEditorPane.setContentType("text/html");
        programScrollPane.setViewportView(programEditorPane);

        verticalSplitPane.setTopComponent(programScrollPane);

        debugPanel.setBorder(null);

        debugLabel.setText("Debug Output");

        debugEditorPane.setContentType("text/html");
        debugScrollPane.setViewportView(debugEditorPane);

        javax.swing.GroupLayout debugPanelLayout =
                new javax.swing.GroupLayout(debugPanel);
        debugPanel.setLayout(debugPanelLayout);
        debugPanelLayout.setHorizontalGroup(debugPanelLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                debugPanelLayout.createSequentialGroup().addComponent(debugLabel).addContainerGap(
                        249, Short.MAX_VALUE)).addComponent(debugScrollPane,
                javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE));
        debugPanelLayout.setVerticalGroup(debugPanelLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                debugPanelLayout.createSequentialGroup().addComponent(debugLabel).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                        debugScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 211,
                        Short.MAX_VALUE)));

        verticalSplitPane.setRightComponent(debugPanel);

        splitPane.setRightComponent(verticalSplitPane);

        frameLabel.setText("Plans");

        refineTraceButton.setText("Disentangle by Traces");

        refineAngelButton.setText("Refinement Query");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 645, Short.MAX_VALUE).addGroup(
                layout.createSequentialGroup().addContainerGap().addGroup(
                        layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                                refineAngelButton,
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 621,
                                Short.MAX_VALUE).addComponent(frameLabel).addGroup(
                                layout.createSequentialGroup().addComponent(
                                        entanglementScrollPane,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 65,
                                        javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                                        splitPane, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        550, Short.MAX_VALUE)).addComponent(
                                refineTraceButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                621, Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 493, Short.MAX_VALUE).addGroup(
                layout.createSequentialGroup().addContainerGap().addComponent(frameLabel).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
                        layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                                entanglementScrollPane,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 382,
                                Short.MAX_VALUE).addComponent(splitPane,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 382,
                                Short.MAX_VALUE)).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                        refineAngelButton).addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(
                        refineTraceButton).addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane debugEditorPane;
    private javax.swing.JLabel debugLabel;
    private javax.swing.JPanel debugPanel;
    private javax.swing.JScrollPane debugScrollPane;
    private javax.swing.JScrollPane entanglementScrollPane;
    private javax.swing.JLabel frameLabel;
    private javax.swing.JScrollPane partitionScrollPane;
    private javax.swing.JEditorPane programEditorPane;
    private javax.swing.JScrollPane programScrollPane;
    private javax.swing.JButton refineAngelButton;
    private javax.swing.JButton refineTraceButton;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JSplitPane verticalSplitPane;

    // End of variables declaration//GEN-END:variables

    protected javax.swing.JScrollPane getPartitionPane() {
        return partitionScrollPane;
    }

    protected javax.swing.JScrollPane getEntanglementPane() {
        return entanglementScrollPane;
    }

    protected javax.swing.JEditorPane getDebugEditorPane() {
        return debugEditorPane;
    }

    protected javax.swing.JScrollPane getDebugScrollPane() {
        return debugScrollPane;
    }

    protected javax.swing.JEditorPane getProgramEditorPane() {
        return programEditorPane;
    }

    protected javax.swing.JScrollPane getProgramScrollPane() {
        return programScrollPane;
    }

    protected javax.swing.JButton getRefineAngelButton() {
        return refineAngelButton;
    };

    protected javax.swing.JButton getRefineTraceButton() {
        return refineTraceButton;
    };
}
