/*
 * To change this template, choose Tools | Templates and open the template in the editor.
 */

/*
 * EntanglementGuiBase.java Created on Sep 27, 2010, 3:18:46 PM
 */

package sketch.entanglement.ui;

import javax.swing.JPanel;
import javax.swing.JComponent;

/**
 * @author shaon
 */
public class EntanglementGuiBase extends javax.swing.JFrame {

    /** Creates new form EntanglementGuiBase */
    public EntanglementGuiBase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameLabel = new javax.swing.JLabel();
        programScrollPane = new javax.swing.JScrollPane();
        programTextArea = new javax.swing.JTextArea();
        debugLabel = new javax.swing.JLabel();
        debugScrollPane = new javax.swing.JScrollPane();
        debugTextArea = new javax.swing.JTextArea();
        entanglementScrollPane = new javax.swing.JScrollPane();
        partitionScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frameLabel.setText("Synthesized Traces");

        programTextArea.setColumns(20);
        programTextArea.setEditable(false);
        programTextArea.setRows(5);
        programScrollPane.setViewportView(programTextArea);

        debugLabel.setText("Debug Output");

        debugTextArea.setColumns(20);
        debugTextArea.setEditable(false);
        debugTextArea.setRows(5);
        debugScrollPane.setViewportView(debugTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frameLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(partitionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entanglementScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(debugLabel)
                            .addComponent(debugScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(programScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partitionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(entanglementScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(programScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(debugLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(debugScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntanglementGuiBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel debugLabel;
    private javax.swing.JScrollPane debugScrollPane;
    private javax.swing.JTextArea debugTextArea;
    private javax.swing.JScrollPane entanglementScrollPane;
    private javax.swing.JLabel frameLabel;
    private javax.swing.JScrollPane partitionScrollPane;
    private javax.swing.JScrollPane programScrollPane;
    private javax.swing.JTextArea programTextArea;
    // End of variables declaration//GEN-END:variables

    protected javax.swing.JScrollPane getPartitionPane() {
        return partitionScrollPane;
    }

    protected javax.swing.JScrollPane getEntanglementPane() {
        return entanglementScrollPane;
    }
}
