package sketch.ui;

import sketch.util.cli.CliAnnotatedOptionGroup;
import sketch.util.cli.CliParameter;

/**
 * command line options for the user interface
 * 
 * @author gatoatigrado (nicholas tung) [email: ntung at ntung]
 * @license This file is licensed under BSD license, available at
 *          http://creativecommons.org/licenses/BSD/. While not required, if you make
 *          changes, please consider contributing back!
 */
public class ScUiOptions extends CliAnnotatedOptionGroup {
    public ScUiOptions() {
        super("ui", "user interface options");
    }

    // @CliParameter(help = "disable the GUI (not recommended)")
    // public boolean noGui;
    @CliParameter(help = "don't automatically display the first solution")
    public boolean noAutoSolnDisp;
    @CliParameter(help = "scala file to generate after \"accept\" is clicked")
    public String acceptFilename = "out.scala";
    @CliParameter(help = "number of lines surrounding the line of interest")
    public int contextLen = 3;
    @CliParameter(help = "maximum amount of context between lines before they are split")
    public int contextSplitLen = 9;
    @CliParameter(help = "number of random stacks to save")
    public int maxRandomStacks = 128;
    @CliParameter(help = "print values generated by counterexamples")
    public boolean printCounterex;
    @CliParameter(help = "regex to split lines")
    public String linesepRegex = "\\n";
    @CliParameter(help = "maximum number of counterexamples and solutions (to avoid overflowing the JList)")
    public int maxListLength = 30000;
    @CliParameter(help = "don't re-execute the program to get skdprint values")
    public boolean noConSkdprint;
    @CliParameter(help = "don't scroll the debug out and source panes to the top left")
    public boolean noScrollTopleft;
    @CliParameter(help = "disable bash color")
    public boolean noBashColor;
    @CliParameter(help = "display each individual evaluated")
    public boolean displayAnimated;
}
